(function(root,factory){
 const api=factory();
 if(typeof module==='object'&&module.exports)module.exports=api;
 if(root)root.RelationshipExpertEngine359=api;
})(typeof window!=='undefined'?window:globalThis,function(){
'use strict';
const priority=['safety_control','boundary_autonomy','trust_evidence','respect_dignity','responsibility_fairness','commitment_clarity','communication_process','attachment_accessibility','desire_intimacy','appreciation_recognition','dating_evaluation','positive_repair'];
const crux={};
const experts={};
function addCrux(id,label,family,p,alt,evidence,action,stop,x=[]){crux[id]={label,family,p,alt,evidence,action,stop,x};}
function addExpert(key,cap,method,probe,move,limit,reads={}){experts[key]={cap,method,probe,move,limit,reads};}
addCrux('safety_control','coercive control or surveillance','safety',[/without consent/,/covert(?:ly)? (?:check|monitor|track)/,/secret(?:ly)? (?:check|monitor|track)/,/demands? .*(?:password|location|phone access)/,/device confiscat/,/punish.*(?:privacy|saying no)/,/stalk/,/isolat.*friends|controls? .*money|restricts? .*movement/],'The access may have been consensual and narrowly tied to repair; the decisive evidence is whether consent was freely revocable without punishment.','Clarify what was accessed, whether consent was freely given, whether rules were reciprocal, and what happened after refusal.','Document the pattern, preserve private support, and change account or location access only when safe.','Do not use a couples disclosure exercise when privacy, refusal, or help-seeking could trigger retaliation.',[/mutual(?:ly)? agreed/,/consensual temporary access/,/agreed not to (?:check|inspect)/]);
addCrux('boundary_autonomy','a boundary or autonomy violation','safety',[/said no|clear no/,/keeps? pushing/,/guilt.*boundary/,/pressure.*sex|sexual coerc/,/will not leave .*alone/,/shows? up uninvited/,/blocked .*but/,/privacy boundary/],'The limit may not have been clear; test that explanation only when direct clarification is safe.','Identify the exact limit, how it was communicated, and whether the response was acceptance, guilt, punishment, or escalation.','State the limit once in behavioral terms and decide what action you will take if it is crossed again.','If setting the boundary may provoke retaliation, prioritize distance, support, and safety planning.');
addCrux('trust_evidence','trust, jealousy, or disputed evidence','trust',[/jealous/,/lied|lying|dishonest|deceiv|betray|affair|cheat/,/trust/,/suspici/,/secret(?:s|ive)?/],'The alarm may reflect uncertainty rather than a verified breach; alternatively, reassurance demands may obscure real deception.','Separate verified facts, explicit agreements, inferences, and the behavior that would genuinely change the conclusion.','Ask one proportionate factual question, name the agreement, and evaluate subsequent consistency.','Do not convert uncertainty into surveillance or use uncertainty to minimize a verified breach.');
addCrux('respect_dignity','respect and dignity under pressure','respect',[/public (?:jab|joke|humiliat|disrespect)/,/in front of friends/,/mock|contempt|insult|belittl|embarrass/,/subtweet|posted .*private|screenshots? .*friends/],'A clumsy isolated misread differs from repeated contempt; the response after impact is named is strong evidence.','Record the behavior, audience, impact, repair attempt, and whether dignity was protected the next time.','Name the dignity violation, request a concrete repair, and set a rule for public and online conduct.','Repeated humiliation or retaliation calls for stronger boundaries, not a better communication script.');
addCrux('responsibility_fairness','ownership, labor, and practical fairness','work',[/household|chore|mental load|invisible labor|planning|logistics|money|financial|bills?|responsib|follow[- ]?through|deadline|task|workload|care work/],'The problem may be an unclear standard or capacity mismatch; repeated nonownership after clarity is different evidence.','Identify the owner, standard, authority, hidden planning load, and who absorbs failure.','Assign one owner, one observable standard, one consultation threshold, and one review date.','Do not use appreciation language to hide chronic free-riding or unsafe financial control.');
addCrux('commitment_clarity','commitment, relationship horizon, or deferred choice','commitment',[/define the relationship|what are we|exclusive|exclusivity|commit|future|marriage|cohabit|move in|engag|relationship horizon|ambigu|situationship|keeps? .*waiting/],'Different pacing can be legitimate; indefinite ambiguity that benefits one person while constraining the other is not merely pacing.','Clarify status, exclusivity, obligations, intended horizon, constraints, and the decision being postponed.','Hold one decision conversation covering status, obligations, next step, and a realistic decision date.','If clarity repeatedly produces no aligned action, continued ambiguity is behavioral information.');
addCrux('communication_process','a failed shared-reality or conflict process','communication',[/communication|misunderst|same page|what .* meant|argument|conflict|critici|correction|defensive|stonewall|shutdown|ai .*judge|chatgpt .*judge|changing .*story/],'The disagreement may concern a real value, resource, or commitment conflict rather than a translation error.','Identify the event, each interpretation, the first escalation move, any repair bid, and the unresolved decision.','Restate the event without motive language, check the other account, and make one specific request.','Clarification is not the intervention when one person knowingly distorts reality or retaliates.');
addCrux('attachment_accessibility','accessibility, reassurance, or pursue-withdraw distress','connection',[/withdraw|pursu|reassur|emotionally unavailable|unreachable|won't talk|wont talk|shuts? down|cling|abandon|alone in the relationship|reach for/],'Distance may reflect overload, incompatibility, or chosen lack of investment rather than an attachment cycle.','Identify the reach, feared meaning, protective response, and whether later reconnection occurs.','Name the cycle without blame, make one bounded request for accessibility, and track follow-through.','Do not ask for vulnerable disclosure when it is mocked, punished, or used as leverage.');
addCrux('desire_intimacy','desire, intimacy, or closeness without coercion','intimacy',[/sex|sexual|desire|passion|intimacy|roommate energy|affection|touch|libido|erotic|dead bedroom|not attracted/],'Desire may reflect health, stress, resentment, pain, or incompatibility rather than insufficient novelty.','Clarify consent, desire discrepancy, health and stress, resentment, welcome affection, and pressure.','Discuss desire outside initiation; name one support, one inhibitor, and one welcome form of closeness.','Pressure, punishment, or bargaining for access makes consent and safety the priority.');
addCrux('appreciation_recognition','recognition, contribution, and correction','appreciation',[/appreciat|gratitude|thank|effort (?:count|notice)|useful|nothing i do|thoughtful|praise|recognition|corrected .*gift|gift .*corrected/],'A contribution can deserve recognition while the outcome still needs correction; praise must not become payment for avoidable incompetence.','Separate contribution, intended benefit, actual impact, agreed standard, and whether recognition and correction shared one moment.','Let specific recognition stand alone; discuss the standard later as a separate request.','Do not require gratitude to excuse chronic poor follow-through, entitlement, or unfair labor.');
addCrux('dating_evaluation','early-dating evaluation and option management','dating',[/first date|second date|early dat|spark|slow burn|\bick\b|dating app|swip|profile|too many options|choice overload|checklist|post-date/],'Slow-burn potential can coexist with clear incompatibility, dread, disrespect, or simply no interest.','Separate observed behavior, felt experience, checklist judgment, comparison, and the decision being avoided.','Use one consistent post-date review and choose either one proportionate additional date or a clear ending.','Do not optimize past coercion, disrespect, persistent dread, or established-partner problems.');
addCrux('positive_repair','a positive repair or strengthening pattern','positive',[/repair(?:ed)? well|came back|apolog|owned .*impact|resolved|worked through|calm.*discuss|healthy boundary|followed through|specific gratitude|positive|green flag|thoughtful/],'One good event is promising evidence, not proof that a contradictory larger pattern has changed.','Name the helpful behavior, its effect, who initiated it, whether it was freely given, and whether it repeated.','Name the behavior and effect, then create a repeatable ritual that does not turn appreciation into debt.','Do not use a positive event to erase unresolved harm or a more frequent contradictory pattern.');
addExpert('Sue Johnson',{attachment_accessibility:1,communication_process:.75,trust_evidence:.55,positive_repair:.8},'This lens follows the cycle from protective reaction to primary fear and attachment need.','What did this mean about whether each person mattered and whether the other person was emotionally reachable?','Each person completes: "When that happened, I feared __; I protected myself by __; the safer reach I can make is __."','Attachment work is a poor fit when coercion, punished vulnerability, or a deferred commitment decision is central.',{attachment_accessibility:'The crux is the reach-and-protect cycle: protest meets distance, and each response confirms the other person\'s fear.',positive_repair:'The important event is restored accessibility: someone turned back, responded, and made the bond reachable again.'});
addExpert('Gottman',{communication_process:1,respect_dignity:.9,responsibility_fairness:.7,appreciation_recognition:.9,positive_repair:1},'This lens treats observable interaction process and accepted repair as more predictive than explanation.','What was the first escalation move, and what happened when either person tried to soften, own impact, or reconnect?','Replay the first two minutes with one specific complaint, one feeling, and one request; record responsibility or counterattack.','Couples process exercises should not be used during coercive control or credible retaliation.',{communication_process:'The crux is the conflict sequence: startup, criticism or complaint, defensiveness, flooding, and whether repair landed.',appreciation_recognition:'The positive bid was overwritten by correction; recognition and the task complaint need separate moments.',positive_repair:'The repair worked because someone reduced defensiveness, accepted influence, or made a bid the other received.'});
addExpert('Esther Perel',{desire_intimacy:1,attachment_accessibility:.55,commitment_clarity:.55,trust_evidence:.65},'This lens asks how security, freedom, identity, admiration, and aliveness are negotiated.','What is each person protecting: certainty, freedom, erotic dignity, identity, or relief from obligation?','Map one condition that creates closeness and one that creates aliveness for each person; change one without increasing pressure.','Autonomy language must not romanticize betrayal, surveillance, coercion, or indefinite avoidance.',{desire_intimacy:'The crux is less about frequency than the conditions for feeling free, curious, desired, and not conscripted.',commitment_clarity:'The tension is whether freedom is negotiated honestly or used as exemption from decisions.',trust_evidence:'Distinguish privacy that preserves personhood from secrecy that evades an agreement.'});
addExpert('Evan Stark',{safety_control:1,boundary_autonomy:1,respect_dignity:.7},'This lens examines cumulative restriction of autonomy and what refusal costs.','Who can refuse, what does refusal cost, are rules reciprocal, and is behavior changing to avoid punishment?','Document the pattern, preserve private support and essential accounts, and plan steps around retaliation risk.','Do not use both-sides framing or joint confrontation when one person controls the conditions of refusal.',{safety_control:'The crux is not reassurance but whether monitoring, intimidation, isolation, or resource control makes autonomy punishable.',boundary_autonomy:'The diagnostic event is the response to refusal: acceptance or guilt, interrogation, punishment, and escalation.'});
addExpert('Scott Stanley',{commitment_clarity:1,responsibility_fairness:.45,dating_evaluation:.55},'This lens separates dedication from constraints and explicit decisions from sliding by inertia.','What was explicitly chosen, what merely happened, and what meaningful decision is deferred?','Write current status, obligations, next decision, and decision date; each person must be free to answer.','Clarity cannot create compatibility, desire, safety, or dedication.',{commitment_clarity:'The crux is a choice nobody made clearly while expectations, dependence, or constraints accumulated.'});
addExpert('Logan Ury',{dating_evaluation:1,commitment_clarity:.35,positive_repair:.35},'This lens checks whether spark fixation, hesitation, romanticizing, or checklist filtering distorts an early-dating decision.','What side of you appeared during contact, and which observed behavior should drive the next decision?','Review ease, curiosity, respect, attraction, and follow-through, then make one bounded dating decision.','This is not advice for coercion, marriages, persistent dread, or settled incompatibility.',{dating_evaluation:'The crux is the gap between the lived interaction and the fast judgment layered onto it: spark, ick, checklist, or fear.'});
addExpert('Eli Finkel',{dating_evaluation:.95,commitment_clarity:.45},'This lens examines option abundance, unrealistic comparison, and expectations relative to relationship investment.','Are alternatives real tested relationships or a composite fantasy, and has this relationship received fair real-world investment?','Use stable criteria, briefly reduce option churn, and evaluate actual interactions rather than profile potential.','App-marketplace advice is irrelevant when apps are inactive or the issue is safety, disrespect, betrayal, or a marriage.',{dating_evaluation:'The crux is an evaluation mindset in which a real person competes with a frictionless composite.'});
addExpert('David Buss',{trust_evidence:.85,commitment_clarity:.8,desire_intimacy:.5,dating_evaluation:.45},'This lens tests horizon, exclusivity, investment, jealousy triggers, and strategic mismatch without making population averages an individual verdict.','Do both people want the same horizon, exclusivity, investment, and exit conditions, and what individual behavior proves it?','Each person states horizon, exclusivity, investment, and deal-breakers; compare answers with conduct.','Population patterns cannot establish motive and must never justify stereotypes, coercion, or dishonesty.',{trust_evidence:'The crux is whether jealousy responds to a verified agreement threat, ambiguous evidence, or mismatched exclusivity.',commitment_clarity:'The issue may reflect different intended horizons rather than a shared plan with poor communication.'});
addExpert('Gabor Mate',{attachment_accessibility:.6,trust_evidence:.55,communication_process:.55},'This lens separates the present event from an older familiar survival meaning while preserving accountability.','Which part belongs to current evidence, and which part has the emotional age of an earlier wound?','Make two columns - present facts and familiar old meaning - regulate first, then address current behavior.','Do not infer trauma from intensity, diagnose the other person, or redirect attention from ongoing harm.');
addExpert('Brene Brown',{communication_process:.7,appreciation_recognition:.55,trust_evidence:.55,respect_dignity:.45},'This lens looks for shame turning an identity fear into blame, perfectionism, defensiveness, or withdrawal.','What would feel exposing to admit if blame and self-protection were unavailable?','Use: "The story I am making up is __; the vulnerable part is __; the reality-check or repair I need is __."','Vulnerability is optional and cannot replace apology, restitution, boundaries, or changed behavior.');
addExpert('Alison Armstrong',{appreciation_recognition:1,responsibility_fairness:.65,positive_repair:.65},'This opt-in gendered education lens separates contribution, impact, comfort, and solution without assigning roles by sex.','Was the unmet need recognition, comfort, competent execution, or shared ownership?','Let recognition stand alone; later name the result, comfort, or ownership standard required.','Treat roles as hypotheses and never demand praise for chronic poor follow-through.',{appreciation_recognition:'The crux is recognition collapsed with evaluation: effort can count while the result still needs a different standard.'});
addExpert('Orion Taraban',{appreciation_recognition:.8,respect_dignity:.7,commitment_clarity:.55},'This lens asks which behaviors current rewards, punishment, silence, access, and rescue make more likely.','What became more rewarding: honesty, effort, testing, withdrawal, withholding, or repair?','List what each person rewards, punishes, ignores, and demands; change one incentive without manipulation.','Incentive language must not turn affection into payment or excuse coercion and contempt.');
addExpert('Louise Perry',{commitment_clarity:.8,dating_evaluation:.6,trust_evidence:.55,respect_dignity:.55},'This lens examines weak norms around commitment, sex, online attention, and public dignity.','Which norm did each person assume, who benefits from ambiguity, and was it freely agreed?','Write a short agreement covering exclusivity, public dignity, online boundaries, sex, and the next decision.','Cultural analysis is less useful when norms are explicit and repair or safety is central.');
addExpert('Marcus Aurelius',{trust_evidence:.7,boundary_autonomy:.7,commitment_clarity:.55,responsibility_fairness:.55,positive_repair:.55,safety_control:.45},'This lens separates fact from judgment and asks which honorable action remains under your control.','What is established fact, what judgment was added, and what action preserves dignity without controlling the other person?','Write the event without adjectives, the judgment attached to it, and one composed action fully within your control.','Stoicism is misused if it suppresses emotion, normalizes mistreatment, or turns endurance into duty.',{safety_control:'Another person\'s suspicion is outside your command; consent, account security, documentation, and your next safe action are not.',trust_evidence:'Separate verified conduct from fear, then choose according to evidence rather than forcing certainty.',appreciation_recognition:'A task judgment need not become a judgment about worth; recognition and correction can be separate.',commitment_clarity:'You cannot command another person to choose a future; you can state the relationship you will participate in.',responsibility_fairness:'Resentment becomes clearer when duties and consequences are named precisely.',positive_repair:'Receive the good event gratefully without making it proof of the future.'});
addExpert('Aristotle',{responsibility_fairness:.8,commitment_clarity:.7,respect_dignity:.7,appreciation_recognition:.65,positive_repair:.7,safety_control:.5},'This lens asks what habits of justice, courage, generosity, truthfulness, and practical friendship the pattern cultivates.','What kind of character and shared life are these repeated actions teaching both people to create?','Name the relevant virtue, define one observable behavior for each person, and evaluate the next instance by conduct.','Virtue language is empty when abstract, moralizing, or falsely symmetrical in an unsafe power imbalance.',{safety_control:'Repeated monitoring cultivates domination, fear, concealment, and submission rather than equal friendship.',trust_evidence:'Trustworthiness is a habit of truthful conduct, not a demand to be believed.',appreciation_recognition:'Fair partnership recognizes contribution while preserving standards and accountable ownership.',commitment_clarity:'Commitment organizes two lives toward a deliberately shared good.',responsibility_fairness:'Justice concerns labor, authority, mental load, recognition, and consequences together.',positive_repair:'Repeated good action becomes character and relationship culture.'});
addExpert('Bell Hooks',{safety_control:.75,boundary_autonomy:.8,respect_dignity:.9,trust_evidence:.7,responsibility_fairness:.7,positive_repair:.65},'This lens evaluates love as care, respect, knowledge, responsibility, trust, and commitment rather than intensity.','Which practice of care, respect, trust, knowledge, responsibility, or commitment is present or absent?','Choose one missing practice and define an observable action that restores mutual dignity without debt or domination.','Love language must not demand empathy from the harmed person while the other refuses responsibility.',{safety_control:'Surveillance replaces trust and knowledge with domination; attachment does not make it loving.',trust_evidence:'Trust is built through truth, reliability, respect, and responsible handling of vulnerability.',appreciation_recognition:'Care includes noticing labor without making gratitude a substitute for justice.',commitment_clarity:'Commitment is enacted responsibility, not possession, intensity, or indefinite promise.',respect_dignity:'Humiliation turns a partner into an object used for status or emotional discharge.',responsibility_fairness:'Love cannot depend on one person\'s invisible service while responsibility stays unequal.',positive_repair:'A loving act matters when care and respect become reliable practice.'});
addExpert('Jane Austen',{respect_dignity:.8,dating_evaluation:.75,commitment_clarity:.65,trust_evidence:.65,positive_repair:.55},'This literary lens treats behavior under inconvenience, embarrassment, temptation, and status pressure as character evidence.','What did this person do when pride, status, inconvenience, or no audience made good behavior more costly?','Keep a character ledger of promise, conduct, humility after correction, regard for others, and repair.','Subtle observation is insufficient when direct safety action or a clear boundary is required.',{safety_control:'Jealous inspection is poor evidence of affection and strong evidence about judgment and respect.',trust_evidence:'Professions are less informative than consistency when convenience or temptation intervenes.',appreciation_recognition:'Good manners make gratitude particular; flattery is abundant and inexpensive.',commitment_clarity:'Courtship intentions become credible through clarity, steadiness, and ordinary inconvenience.',respect_dignity:'Company reveals whether wit and status outrank loyalty and consideration.',responsibility_fairness:'Domestic character appears in ordinary reliability, not dramatic declarations.',positive_repair:'One gracious event is promising; repeated consideration under inconvenience is persuasive.'});
experts['Call Her Daddy']=Object.assign(addExpert('Call Her Daddy',{dating_evaluation:.25,commitment_clarity:.2},'This entertainment-media contrast emphasizes leverage, standards, and protection from premature investment.','What would direct communication reveal that a test, delay, or power move would obscure?','Keep the standard and remove the game: state it once, then judge behavior.','If both people optimize leverage, expect more testing, ambiguity, and distrust.')||experts['Call Her Daddy'],{contrast:true});
experts['Red-pill']=Object.assign(addExpert('Red-pill',{dating_evaluation:.1,commitment_clarity:.1},'This ideological contrast reduces the event to status, bargaining power, and generalized sex differences.','Which claims survive when every statement about men or women becomes a claim about this individual?','Audit actions, agreements, consistency, consent, and reciprocity only.','Discard the framing when it increases contempt, dominance, coercion, or tolerance for disrespect.')||experts['Red-pill'],{contrast:true});
const stageText={early:'Keep the test proportionate to early dating; do not demand established-partner access.',ambiguous:'The ambiguity itself is evidence when expectations keep accumulating.',committed:'Evaluate this against explicit agreements and accumulated trust.',married:'Address the durable system of routines, roles, resources, intimacy, and repair rather than screening the partner like a date.',boundary:'Prioritize enforceable limits and exposure reduction over mutual-growth exercises.',nonromantic:'Translate this into role, process, documentation, and appropriate boundaries.'};
const recurrenceText={first:'Treat this as evidence, not yet a settled trait.',occasional:'Compare context and repair before calling it a stable pattern.',recurring:'Because this recurs, explanations now matter less than changed behavior.',core:'This is structural; evaluate the relationship system rather than another isolated apology.'};
function expertFor(name){const hit=Object.keys(experts).find(key=>String(name||'').includes(key));return hit?experts[hit]:null;}
function classifyStage(profile){const t=`${profile?.rtype||''} ${profile?.desiredOutcome||''}`.toLowerCase();if(/work|boss|cowork|employee|family|friend|pet/.test(t))return'nonromantic';if(/boundary|do not date|no contact/.test(t))return'boundary';if(/married|husband|wife|spouse|marriage/.test(t))return'married';if(/long-term|fianc|committed|exclusive|partner/.test(t))return'committed';if(/situationship|ambiguous/.test(t))return'ambiguous';return'early';}
function classifyRecurrence(v){const t=String(v||'').toLowerCase();if(/core|constant|chronic|always/.test(t))return'core';if(/recurr|repeat|often|many/.test(t))return'recurring';if(/occas|sometimes|more than once/.test(t))return'occasional';return'first';}
function selectedText(ctx){const i=ctx?.issue||{};return[i.type,i.title,i.event,i.story,i.aggrieved,i.recurrence].filter(Boolean).join(' ').toLowerCase();}
function polarity(issue,text){const p=String(issue?.polarity||'').toLowerCase();if(p==='positive'||p==='negative')return p;if(/never appreciat|not appreciat|lack of appreciat|followed by correction|thoughtful .*ignored/.test(text))return'negative';if(/positive|repair(?:ed)? well|specific gratitude|healthy boundary|apologized|came back|followed through/.test(text))return'positive';return'mixed';}
function analyze(ctx){
 const issue=ctx?.issue||{},text=selectedText(ctx),scores={};
 for(const[id,d]of Object.entries(crux)){let n=0;for(const re of d.p)if(re.test(text))n++;for(const re of d.x||[])if(re.test(text))n-=3;scores[id]=n;}
 const pol=polarity(issue,text);if(pol==='positive')scores.positive_repair+=.8;
 const ranked=priority.map((id,index)=>({id,score:scores[id]||0,index})).sort((a,b)=>b.score-a.score||a.index-b.index);
 let id=ranked[0].score>0?ranked[0].id:(pol==='positive'?'positive_repair':'communication_process');
 if(pol==='positive'&&ranked[0].score<=.8)id='positive_repair';
 const secondary=ranked.find(x=>x.id!==id&&x.score>0)?.id||null,detail=String(issue.event||issue.story||issue.title||issue.type||'No detailed event was entered.').trim();
 return{crux:id,secondary,stage:classifyStage(ctx?.profile),recurrence:classifyRecurrence(issue.recurrence),polarity:pol,safetyLevel:id==='safety_control'?'acute':id==='boundary_autonomy'?'caution':'none',detail,text,confidence:Math.min(1,.25+ranked[0].score*.16+(detail.length>45?.16:0)+(issue.type?.length?.08:0)),scores,label:crux[id].label};
}
function score(row,ctx){const a=analyze(ctx),e=expertFor(row?.name);if(!e)return 0;if(e.contrast)return-1000;let n=45*(e.cap[a.crux]||0)+15*(e.cap[a.secondary]||0)+8*(a.polarity==='positive'?(e.cap.positive_repair||.2):.5)+8*(/recurring|core/.test(a.recurrence)?1:.5);if(a.stage==='married'&&/Logan Ury|Eli Finkel/.test(row.name))n-=50;if(a.safetyLevel!=='none'&&!/Evan Stark|Bell Hooks/.test(row.name))n-=35;return n;}
function rank(rows,ctx){return rows.filter(r=>!expertFor(r.name)?.contrast).slice().sort((a,b)=>score(b,ctx)-score(a,ctx)||String(a.name).localeCompare(String(b.name)));}
function compose(row,ctx){
 const a=analyze(ctx),e=expertFor(row?.name);if(!e)return null;const c=crux[a.crux],read=e.reads[a.crux]||`The crux is ${c.label}. ${e.method}`;
 const positive=a.polarity==='positive'&&a.crux!=='positive_repair'?' This is positive evidence within that subject, so reinforce the exact behavior without treating one event as proof of the relationship.':'';
 let experiment=e.move,failure=`${c.stop} ${e.limit}`;
 if(a.safetyLevel==='acute'&&!String(row.name).includes('Evan Stark')){experiment='Do not run this lens as a relationship exercise yet. Document the pattern, preserve private support, and assess retaliation risk before confrontation.';failure='Safety and autonomy take precedence over this framework until the controlling pattern no longer shapes what can be said or refused.';}
 return{analysis:a,crux:c.label,frame:`${read}${positive} ${stageText[a.stage]} ${recurrenceText[a.recurrence]}`.trim(),challenge:c.alt,evidence:c.evidence,question:e.probe,experiment,failure,limitation:e.limit,fit:score(row,ctx)};
}
function fitLabel(row,ctx){const n=score(row,ctx),a=analyze(ctx);if(a.confidence<.5)return'Exploratory fit';return n>=40?'High fit':n>=20?'Moderate fit':'Low fit';}
return{analyze,score,rank,compose,fitLabel,crux,experts};
});
