const STORAGE_KEY="relationship_intelligence_pwa_v2";
const greenDefs=[["warmth","Warmth","Emotional warmth, ease, affection."],["kindness","Kindness","Basic goodness toward you and others."],["respect","Respect","You feel respected rather than mocked, managed, or tested."],["reciprocity","Reciprocity","Interest and effort move both directions."],["curiosity","Curiosity","They actually want to know you."],["stability","Emotional stability","Grounded enough to build with."],["peace","Peace after contact","Afterward you feel peaceful, not anxious or humiliated."],["attraction","Attraction","Physical / romantic pull."]];
const riskDefs=[["chaos","Chaos / drama","Volatility, crisis, or confusing energy."],["trauma","Early trauma dumping","Heavy disclosure before trust exists."],["entitlement","Entitlement","Expects without appreciating."],["family","Family disrespect","Contempt toward family/parents that may signal broader contempt."],["social","Social-media validation","Attention-seeking or comparison energy."],["inconsistent","Inconsistent communication","Words and effort fluctuate in a destabilizing way."]];
let state=loadState();function $(id){return document.getElementById(id)}
function loadState(){try{let raw=localStorage.getItem(STORAGE_KEY);if(raw)return JSON.parse(raw);let old=localStorage.getItem("relationship_intelligence_pwa_v1");if(old)return migrate(JSON.parse(old))}catch(e){}return{currentId:null,profiles:[]}}
function migrate(s){s.profiles=(s.profiles||[]).map(p=>({...p,evidence:p.evidence||"",interpretation:p.interpretation||"",rtype:p.rtype==="Potential romantic partner"?"Romantic prospect":(p.rtype||"Romantic prospect")}));return s}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));$("status").textContent="Autosaved locally"}
function uid(){return"p_"+Date.now()+"_"+Math.random().toString(16).slice(2)}
function blankProfile(){let p={id:uid(),name:"",rtype:"Romantic prospect",met:"Soccer",impression:"",evidence:"",interpretation:"",notes:"",green:{},risk:{}};greenDefs.forEach(([k])=>p.green[k]=5);riskDefs.forEach(([k])=>p.risk[k]=3);return p}
function currentProfile(){if(!state.profiles.length){let p=blankProfile();state.profiles.push(p);state.currentId=p.id}return state.profiles.find(p=>p.id===state.currentId)||state.profiles[0]}
function renderSliders(){$("greenSliders").innerHTML=greenDefs.map(([k,l,h])=>sliderHTML("green",k,l,h,5)).join("");$("riskSliders").innerHTML=riskDefs.map(([k,l,h])=>sliderHTML("risk",k,l,h,3)).join("")}
function sliderHTML(g,k,l,h,d){return`<div class="slider"><div class="sliderTop"><b>${l}</b><span class="bubble" id="${g}_${k}_value">${d}</span></div><div class="small">${h}</div><input type="range" min="0" max="10" value="${d}" id="${g}_${k}"></div>`}
function fillForm(){let p=currentProfile();$("profileTitle").textContent="Profile: "+(p.name||"Untitled");["name","rtype","met","impression","evidence","interpretation","notes"].forEach(id=>$(id).value=p[id]||"");if(!p.rtype)$("rtype").value="Romantic prospect";if(!p.met)$("met").value="Soccer";greenDefs.forEach(([k])=>{let v=p.green?.[k]??5;$(`green_${k}`).value=v;$(`green_${k}_value`).textContent=v});riskDefs.forEach(([k])=>{let v=p.risk?.[k]??3;$(`risk_${k}`).value=v;$(`risk_${k}_value`).textContent=v})}
function collectForm(){let p=currentProfile();["name","rtype","met","impression","evidence","interpretation","notes"].forEach(id=>p[id]=$(id).value);greenDefs.forEach(([k])=>p.green[k]=Number($(`green_${k}`).value));riskDefs.forEach(([k])=>p.risk[k]=Number($(`risk_${k}`).value))}
function avg(obj,defs){return defs.reduce((s,[k])=>s+Number(obj[k]||0),0)/defs.length}
function metrics(p){let g=avg(p.green,greenDefs),r=avg(p.risk,riskDefs);let discernment=Math.round(Math.max(0,Math.min(100,g*10-r*4)));let peaceIndex=Math.round(Math.max(0,Math.min(100,p.green.peace*3.5+p.green.respect*2+p.green.warmth*1.5+p.green.reciprocity*1.5+p.green.stability*1.5-p.risk.chaos*1.5-p.risk.inconsistent-p.risk.trauma*.8)));return{greenAvg:g,riskAvg:r,discernment,peaceIndex}}
function updateReadout(){let p=currentProfile(),m=metrics(p);$("meterFill").style.width=m.discernment+"%";$("peaceIndex").textContent=m.peaceIndex;$("peacePhrase").textContent=m.peaceIndex>=75?"Calming, respectful, emotionally low-cost.":m.peaceIndex>=55?"Worth exploring, but watch whether calm increases.":m.peaceIndex>=35?"Exciting but not yet peaceful. Slow down.":"Low peace signal. Attraction may be masking emotional cost.";let title="Proceed carefully",cls="",text="Keep learning without outrunning the evidence.";if(m.discernment>=70&&p.green.peace>=7&&p.green.respect>=7&&m.riskAvg<=4){title="Worth continuing to explore";cls="good";text="Warmth, respect, and low chaos are present. Keep observing slowly."}else if(m.discernment<=40||p.risk.chaos>=8||p.risk.inconsistent>=8){title="Likely mismatch or boundaries needed";cls="bad";text="This pattern may cost too much peace. Attraction should not override chaos."}if((p.rtype||"").includes("Do not date")){title="Boundaries-first relationship";cls="";text="This is not for romance escalation. Organize around clarity and boundaries."}$("readout").className="readout "+cls;$("readout").innerHTML=`<b>${title}</b><br>Discernment Score: <b>${m.discernment}/100</b><br>${text}<div class="small">Green avg: ${m.greenAvg.toFixed(1)} / Risk avg: ${m.riskAvg.toFixed(1)}</div>`;updateGuidance(p);updateAI(p,m);drawRadar(p)}
function updateGuidance(p){let tips=[];if(p.green.warmth>=7)tips.push("Warmth is a positive signal: connection may be nourishing, not just exciting.");if(p.green.peace<=4)tips.push("Low peace after contact matters. Your body may be noticing emotional cost.");if(p.risk.trauma>=7)tips.push("Early heavy disclosure can create false intimacy. Compassion is fine; pacing still matters.");if(p.risk.chaos>=7)tips.push("Chaos matters because trust requires stability, repair, and predictability.");if(p.green.reciprocity<=4)tips.push("Low reciprocity means you may be carrying the interaction.");if(!tips.length)tips.push("Keep collecting concrete observations. One interaction is evidence, not a verdict.");$("guidance").innerHTML=tips.map(t=>`<div class="guide">${t}</div>`).join("")}
function updateAI(p,m){let archetype="Mixed / unclear";if(p.green.attraction>=7&&m.peaceIndex<45)archetype="High attraction, low peace";else if(p.green.warmth>=7&&p.green.respect>=7&&m.peaceIndex>=70)archetype="Warm and stabilizing";else if(p.risk.chaos>=7||p.risk.inconsistent>=7)archetype="Chaos caution";else if(p.green.reciprocity<=4)archetype="One-sided effort risk";let interp=(p.rtype||"").includes("Do not date")?"This is a boundaries-and-clarity profile, not a romance profile.":p.green.attraction>=8&&m.peaceIndex<=45?"Attraction is high, but peace is weak. This is where people over-invest early.":m.peaceIndex>=75?"The profile suggests low emotional cost and decent relational safety.":p.risk.trauma>=7?"Heavy early disclosure may be vulnerability, but it can accelerate false intimacy.":"The profile is not decisive yet. Watch whether more contact increases peace or confusion.";let next=m.peaceIndex<40?"Slow down. Look for stability and reciprocity before investing more.":p.risk.chaos>=7?"Observe boundaries and consistency. Avoid becoming a rescuer.":p.green.reciprocity<=4?"Ask one open question and watch whether they ask about you.":"Continue with a low-pressure interaction and log how you feel afterward.";$("aiInterpretation").innerHTML=`<p><b>Current pattern:</b> ${archetype}.</p><p><b>Interpretation:</b> ${interp}</p><p><b>Best next move:</b> ${next}</p><p><b>Evidence entered:</b> ${p.evidence?escapeHTML(p.evidence).slice(0,500):"none yet. Add facts to make this less vibes-based."}</p>${p.interpretation?`<p><b>Your hypothesis:</b> ${escapeHTML(p.interpretation).slice(0,500)}</p>`:""}`}
function drawRadar(p){let c=$("radar"),ctx=c.getContext("2d"),w=c.width,h=c.height,cx=w/2,cy=h/2,R=150;ctx.clearRect(0,0,w,h);let axes=[["Warmth",p.green.warmth],["Respect",p.green.respect],["Reciprocity",p.green.reciprocity],["Stability",p.green.stability],["Peace",p.green.peace],["Attraction",p.green.attraction],["Low Chaos",10-p.risk.chaos],["Low Inconsistency",10-p.risk.inconsistent]],n=axes.length;ctx.font="12px -apple-system,BlinkMacSystemFont,Segoe UI,Arial";ctx.textAlign="center";ctx.textBaseline="middle";for(let ring=1;ring<=5;ring++){ctx.beginPath();for(let i=0;i<n;i++){let a=-Math.PI/2+i*2*Math.PI/n,r=R*ring/5,x=cx+Math.cos(a)*r,y=cy+Math.sin(a)*r;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath();ctx.strokeStyle="#ded6c9";ctx.stroke()}axes.forEach(([label],i)=>{let a=-Math.PI/2+i*2*Math.PI/n;ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(cx+Math.cos(a)*R,cy+Math.sin(a)*R);ctx.strokeStyle="#e8dfd2";ctx.stroke();ctx.fillStyle="#5f574e";ctx.fillText(label,cx+Math.cos(a)*(R+36),cy+Math.sin(a)*(R+30))});ctx.beginPath();axes.forEach(([_,val],i)=>{let a=-Math.PI/2+i*2*Math.PI/n,r=R*Math.max(0,Math.min(10,val))/10,x=cx+Math.cos(a)*r,y=cy+Math.sin(a)*r;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.closePath();ctx.fillStyle="rgba(129,91,51,.22)";ctx.fill();ctx.strokeStyle="#815b33";ctx.lineWidth=3;ctx.stroke();ctx.lineWidth=1}
function renderProfiles(){let list=$("profileList");list.innerHTML="<h3>Saved profiles</h3>";state.profiles.forEach(p=>{let b=document.createElement("button");b.className="profile"+(p.id===state.currentId?" active":"");b.innerHTML=`<b>${p.name||"Untitled"}</b><br><span class="small">${p.rtype||""} · ${p.met||""}</span>`;b.onclick=()=>{collectForm();state.currentId=p.id;saveState();fillForm();renderProfiles();updateReadout()};list.appendChild(b)})}
function onAnyChange(){collectForm();saveState();renderProfiles();updateReadout()}
function bindEvents(){["name","rtype","met","impression","evidence","interpretation","notes"].forEach(id=>{$(id).addEventListener("input",onAnyChange);$(id).addEventListener("change",onAnyChange)});greenDefs.forEach(([k])=>$(`green_${k}`).addEventListener("input",()=>{$(`green_${k}_value`).textContent=$(`green_${k}`).value;onAnyChange()}));riskDefs.forEach(([k])=>$(`risk_${k}`).addEventListener("input",()=>{$(`risk_${k}_value`).textContent=$(`risk_${k}`).value;onAnyChange()}));$("newBtn").onclick=()=>{collectForm();let p=blankProfile();state.profiles.push(p);state.currentId=p.id;saveState();fillForm();renderProfiles();updateReadout()};$("exportBtn").onclick=()=>{collectForm();saveState();let blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="relationship-intelligence-backup.json";a.click()};$("importFile").onchange=e=>{let file=e.target.files[0];if(!file)return;let reader=new FileReader();reader.onload=()=>{try{let imported=JSON.parse(reader.result);if(!Array.isArray(imported.profiles))throw new Error();state=imported;if(!state.currentId&&state.profiles[0])state.currentId=state.profiles[0].id;saveState();fillForm();renderProfiles();updateReadout()}catch(err){alert("Could not import that backup file.")}};reader.readAsText(file)}}
function escapeHTML(s){return s.replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[ch]))}
function init(){renderSliders();currentProfile();bindEvents();fillForm();renderProfiles();updateReadout();saveState();$("status").textContent="App loaded. Autosave active."}
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js").catch(()=>{}));init();